import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";

import { discoverJobs } from "./discover.js";
import { MANIFEST_FILENAME, type Manifest, type ManifestJobEntry } from "./types.js";

const GENERATED_MARKER = "AUTO-GENERATED by cronify. Do not edit — run `cronify generate` to regenerate.";

export interface GenerateResult {
  manifest: Manifest;
  routesWritten: string[];
  routesRemoved: string[];
}

function resolveAppDir(root: string): string {
  if (existsSync(join(root, "src", "app"))) return join(root, "src", "app");
  if (existsSync(join(root, "app"))) return join(root, "app");
  throw new Error(
    `cronify: couldn't find a Next.js App Router directory ("app/" or "src/app/") under ${root}.`,
  );
}

function routeFilePath(appDir: string, jobId: string): string {
  return join(appDir, "api", "cron", jobId, "route.ts");
}

function writeRouteFile(appDir: string, sourceFile: string, jobId: string): string {
  const target = routeFilePath(appDir, jobId);
  mkdirSync(dirname(target), { recursive: true });

  const importPath = relative(dirname(target), sourceFile).replace(/\.ts$/, "").replace(/\\/g, "/");
  const specifier = importPath.startsWith(".") ? importPath : `./${importPath}`;

  const contents = `// ${GENERATED_MARKER}
import job from "${specifier}";
import { createRouteHandler } from "cronify/server";

export const { GET, POST } = createRouteHandler(job);
`;
  writeFileSync(target, contents, "utf8");
  return target;
}

function readPreviousManifest(root: string): Manifest | null {
  const path = join(root, MANIFEST_FILENAME);
  if (!existsSync(path)) return null;
  try {
    return JSON.parse(readFileSync(path, "utf8")) as Manifest;
  } catch {
    return null;
  }
}

/** Removes generated routes for jobs that disappeared, but only files we recognize as our own. */
function removeStaleRoutes(appDir: string, previous: Manifest | null, currentIds: Set<string>): string[] {
  if (!previous) return [];
  const removed: string[] = [];
  for (const job of previous.jobs) {
    if (currentIds.has(job.id)) continue;
    const routeFile = routeFilePath(appDir, job.id);
    if (!existsSync(routeFile)) continue;
    const contents = readFileSync(routeFile, "utf8");
    if (!contents.includes(GENERATED_MARKER)) continue;
    rmSync(dirname(routeFile), { recursive: true, force: true });
    removed.push(routeFile);
  }
  return removed;
}

/**
 * Discovers jobs under `<root>/cron`, writes a route file per job under the
 * App Router directory, removes routes for jobs that were removed since the
 * last run, and writes `.cron-manifest.json`. Idempotent — safe to rerun.
 */
export function generate(root: string = process.cwd()): GenerateResult {
  const cronDir = join(root, "cron");
  if (!existsSync(cronDir)) {
    throw new Error(`cronify: no "cron/" directory found at ${root}. Create it and add defineJob() files.`);
  }

  const appDir = resolveAppDir(root);
  const discovered = discoverJobs(cronDir);

  const previous = readPreviousManifest(root);
  const currentIds = new Set(discovered.map((job) => job.id));
  const routesRemoved = removeStaleRoutes(appDir, previous, currentIds);

  const routesWritten = discovered.map((job) => writeRouteFile(appDir, job.sourceFile, job.id));

  const jobs: ManifestJobEntry[] = discovered.map(({ sourceFile: _sourceFile, ...entry }) => entry);
  const manifest: Manifest = {
    version: 1,
    generatedAt: new Date().toISOString(),
    jobs,
  };
  writeFileSync(join(root, MANIFEST_FILENAME), `${JSON.stringify(manifest, null, 2)}\n`, "utf8");

  return { manifest, routesWritten, routesRemoved };
}
